# Generated by Django 5.2.4 on 2025-07-29 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('reservas', '0005_reserva_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-creado_en']},
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='fecha_emision',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='monto_consumos',
            new_name='total_consumo',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='monto_estadia',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
        migrations.AddField(
            model_name='factura',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_estadia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='reservas.reserva'),
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura')),
            ],
            options={
                'ordering': ['factura', 'descripcion'],
            },
        ),
    ]
