# Generated by Django 5.2.4 on 2025-07-28 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_dni_alter_cliente_email'),
        ('habitaciones', '0001_initial'),
        ('reservas', '0003_alter_reserva_costo_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_entrada']},
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cliente'], name='reservas_re_cliente_e986e9_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['habitacion'], name='reservas_re_habitac_22af32_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_entrada'], name='reservas_re_fecha_e_fa68b5_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_salida'], name='reservas_re_fecha_s_4c572c_idx'),
        ),
    ]
