# Generated by Django 5.2.4 on 2025-07-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('ocupado', 'Ocupado'), ('finalizado', 'Finalizado')], default='reservado', max_length=20),
        ),
    ]
