# Generated by Django 5.2.4 on 2025-07-31 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_cantidad_adultos_reserva_cantidad_ninios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cantidad_ninios',
            new_name='cantidad_ninos',
        ),
    ]
