# Generated by Django 5.2.4 on 2025-07-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('doble', 'Doble'), ('matrimonial', 'Matrimonial'), ('suite', 'Suite'), ('triple', 'Triple')], max_length=20)),
                ('costo_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('caracteristicas', models.TextField(blank=True)),
            ],
        ),
    ]
