# Generated by Django 5.2.4 on 2025-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='capacidad_personas',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
