# Generated by Django 5.2.4 on 2025-07-30 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huespedes_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huespedes_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['dni'], name='huespedes_h_dni_7ec355_idx'), models.Index(fields=['apellido'], name='huespedes_h_apellid_0f36fb_idx')],
            },
        ),
    ]
