# Generated by Django 5.2.4 on 2025-07-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
