# Generated by Django 5.2.4 on 2025-07-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_eliminado_cliente_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(error_messages={'unique': 'Ya existe un cliente con este DNI.'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un cliente con este email.'}, max_length=254, unique=True),
        ),
    ]
